# Generated by Django 5.0.6 on 2024-07-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Pendiente',
        ),
        migrations.RenameField(
            model_name='pendiente',
            old_name='is_resolved',
            new_name='resolved',
        ),
    ]
